### ISSUE TITLE
Replay attack

### ISSUE THREAD

**Issue by losfair** [maxmunzel/kvass#2]
It looks like the `Encrypt`:

https://github.com/maxmunzel/kvass/blob/ca4f18d9e5e2c9ddeb19c2cefa85d509137df863/src/sqlite_persistance.go#L229

and `DecryptData`:

https://github.com/maxmunzel/kvass/blob/ca4f18d9e5e2c9ddeb19c2cefa85d509137df863/src/sqlite_persistance.go#L201

methods use a pre-shared key to encrypt and decrypt data directly, without any form of key exchange happening. This can lead to replay attacks, making it possible for a MITM to replay a previously sent `/push` request to overwrite an existing file.

My suggestion is to either use a standard protocol like TLS or implement your own (EC)DH to exchange keys before each request.

**Comment by maxmunzel** [comment]
Hi Losfair, 

thanks for raising the issue. The underlying datatype that is implemented on top of the sqlite database is a CRDT, which 
makes every transaction (get/set/rm) idempotent. The key logic is in the `UpdateOn` function, that is used to merge updates into the current state:

https://github.com/maxmunzel/kvass/blob/ca4f18d9e5e2c9ddeb19c2cefa85d509137df863/src/sqlite_persistance.go#L295

You are right, in that its always a good idea to defend oneself in depth and have non-replayability in addition to a robust datatype. As ~losfair, oh wait that's~ [you](https://news.ycombinator.com/item?id=32212829) pointed out, its advisable to use TLS with a PSK once it becomes available. But for the moment, I'd consider it low-priority as long as the CRDT is implemented correctly.

**Comment by maxmunzel** [comment]
You could also use a https reverse-proxy like [caddy](https://caddyserver.com) in front of the endpoints. Then GCM just serves as a fancy MAC. HTTPS is desirable in general for the shareable link so I guess I'll implement it at some point...

**Comment by indiv0** [comment]
@maxmunzel do you have any details on the CRDT? I'd love to know more about how it works. I'm unfamiliar with CRDTs in general. Is there a document you'd recommend to get familiar with how to use them for a system like this?

**Comment by maxmunzel** [comment]
Hi @indiv0, I updated the readme about how kvass uses them. I'd love to hear your feedback. On CRDT's in general, 
I like the original paper: https://pages.lip6.fr/Marc.Shapiro/papers/RR-7687.pdf (Have a look at the examples)
