### ISSUE TITLE
Error handling could be improved.

### ISSUE THREAD

**Issue by skx** [maxmunzel/kvass#3]
It seems the following function is not used:

```
func panicIfNonNil(err error) {
```

But worryingly several areas of code will simply terminate with a `panic` on errors, which is not the kind of thing you'd like to see in the server-Push function (which would presumably break server-to-server communication).

**Comment by maxmunzel** [comment]
Hi skx, thanks for opening an issue.

I roughly categorised error like this:

Things that should really not go wrong (reading random bytes from the OS, performing sqlite operations,...). -> they always panic, as they indicate that something is fundamentally broken.

Things that are expected to go wrong from time to time (e.g. anything network related) -> those should bubble up and result in a warning. I might be a little more liberal here when they happen on the top level (cli code).

Do you see any specific instances of `panic()` that violate these rules?

**Comment by skx** [comment]
No, nothing that jumps out if you approach it like that.

(I just like to be "good" and catch "everything".  So I'll close this if you've got an approach you're happy with.  Cute project though :)
