### ISSUE TITLE
Provide versions / releases

### ISSUE THREAD

**Issue by hashworks** [maxmunzel/kvass#5]
It would be great if you could provide versions with git tags, so one can build packages for linux distributions.

**Comment by psydvl** [comment]
@hashworks you can always use `@latest` as version tag

**Comment by maxmunzel** [comment]
Hi Hashworks, thanks for raising the issue. Here you go: https://github.com/maxmunzel/kvass/releases/tag/v1.0.0

Let me know if kvass finds its way into a linux distro :)
