### ISSUE TITLE
Remember users about binding to 0.0.0.0 if they want external access

### ISSUE THREAD

**Issue by hugows** [maxmunzel/kvass#6]
Hey! 

Thanks for this tool! I was trying to set this up on the Oracle Cloud Free Tier, and unfortunately took too long to remember about this - thought I was having a firewall issue until this clicked up!

Thanks!

**Comment by maxmunzel** [comment]
Hi Hugo, thanks for opening an issue!

Just to clarify: What have you tried to bind to instead? I hoped that the default value in the helpsstring was reference enough:

```
❯ kvass serve -h
kvass serve [--db=string] [--bind=string]

Description:
    start in server mode

Options:
        --db     the database file to use (default: ~/.kvassdb.sqlite)
        --bind   bind address (default: localhost:8000)
```

Python on the other hand has an even simpler usage for their http server, albeit at the cost of a more complex cli:

```
❯ python3 -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
^C
Keyboard interrupt received, exiting.
❯ python3 -m http.server -h
usage: server.py [-h] [--cgi] [--bind ADDRESS] [--directory DIRECTORY] [port]

positional arguments:
  port                  specify alternate port (default: 8000)

options:
  -h, --help            show this help message and exit
  --cgi                 run as CGI server
  --bind ADDRESS, -b ADDRESS
                        specify alternate bind address (default: all
                        interfaces)
  --directory DIRECTORY, -d DIRECTORY
                        specify alternate directory (default: current
                        directory)
```

I can imagine adapting their interface including the `Serving on :: port 8000 (http://[::]:8000/) ...` message. Would that helped your situation?

**Comment by hugows** [comment]
I wanted to avoid port 8000 because its in use in my server.

So, I first looked for a `port` arg, and then found the `bind` arg. Then I called kvass with `--bind=localhost:7777` and started messing with the firewall settings and the Cloud provider network settings and firewall too.

Much later I actually ran the python mini server just like you mentioned, on the same port 7777, and since that worked I then remembered about having to bind to 0.0.0.0....

**Comment by maxmunzel** [comment]
`Serving on :: port 8000 (http://[::]:8000/) ...` would have resolved the confusion? 

In this case I'd add a log message like this.

If you think the separate port cli like in python is preferable, I'd be happy to merge a PR.

**Comment by hugows** [comment]
To be honest I feel like the `::` doesn't mean anything to most people? I only remember it due to using Python...

But to bind on all interfaces would be a better default for people like me - for sure.

**Comment by maxmunzel** [comment]
I agree that the CLI version that has separate port and bind options is the easiest option to use, but I don't really fancy implementing it myself at the moment. -> If you want to make a PR I'm happy to review and merge it.

A `Accepting connections on 0.0.0.0:8000` message would be a no brainer to implement and I would do it myself.

I'm not trying to be dismissive but I'm in exam phase right now and a little short on time.

**Comment by maxmunzel** [comment]
Hi Hugo, I seem to have overlooked that the default is indeed `localhost`, not `0.0.0.0`. Sorry for that!

I changed it now, improved the help string and echo the bind when starting `kvass serve`. I think this should clear up 
the usage and avoid confusion. Thanks again for bringing up the issue and have a nice day :)

```
❯ kvass serve -h
kvass serve [--db=string] [--bind=string]

Description:
    start in server mode

Options:
        --db     the database file to use (default: ~/.kvassdb.sqlite)
        --bind   bind address (default: "0.0.0.0:8000" meaning all interfaces, port 8000)
❯ kvass serve
2022/07/26 18:10:45 Server started and listening on 0.0.0.0:8000
```
